- aii-core/src/main/perl/aii-web.cgi
* Some variables were not initialized
* add support for JSON profiles via GET variable
> aii-web: FIX errors and add JSON profiles suport

- aii-ks/src/main/perl/ks.pm
This is to avoid timeout of the service (and the cleanup that comes with it)
Fixes #100
> aii-ks: ks-post-reboot should have proper unit on systemd 

- aii-opennebula/src/main/pan/quattor/aii/opennebula/default.pan
- aii-opennebula/src/main/pan/quattor/aii/opennebula/schema.pan
- aii-opennebula/src/main/perl/opennebula.pm
- aii-opennebula/src/main/perl/opennebula.pod
- aii-opennebula/src/test/perl/basic.t
- aii-opennebula/src/test/perl/vmtemplate.t
- aii-opennebula/src/test/resources/basic.pan
- aii-opennebula/src/test/resources/kickstart.pan
This PR includes a new configure hook:
* #107  : Update OpenNebula templates from configure hook 
It was included a new hook to create/update Opennebula templates so now:
* configure: create/update vm/vnet templates. It also generates new vm images.
* install: instantiate/stop vm
* remove: remove images/templates/vm
**NOTE:** This PR requires aii-pxelinux `Configure` hook to work. https://github.com/quattor/aii/pull/114
> aii-opennebula: Include new install hook

- aii-ks/src/main/pan/quattor/aii/ks/variants/el7.pan
Matches the template library expectation! Old name `rhel7rc` clearly inappropriate...
> aii-ks: Correct el7 variant from rhel7rc to el7

- aii-pxelinux/src/main/pan/quattor/aii/pxelinux/schema.pan
- aii-pxelinux/src/test/perl/pxelinux_ks_systemd_ksdevice.t
- aii-pxelinux/src/test/resources/pxelinux_ks_ksdevice_systemd_scheme_1.pan
- aii-pxelinux/src/test/resources/pxelinux_ks_ksdevice_systemd_scheme_2.pan
- aii-pxelinux/src/test/resources/pxelinux_ks_ksdevice_systemd_scheme_3.pan
- aii-pxelinux/src/test/resources/pxelinux_ks_ksdevice_systemd_scheme_4.pan
As documented at:
* http://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/
* https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/ch-Consistent_Network_Device_Naming.html
This is the AII counterpart to quattor/configuration-modules-core#528.
> Support all five systemd device naming schemes

- aii-ks/src/main/perl/ks.pm
- aii-ks/src/test/perl/kickstart_proxy.t
- aii-ks/src/test/resources/kickstart_noproxy.pan
- aii-ks/src/test/resources/kickstart_proxy.pan
When the `spma` `proxy` attribute is used to toggle proxy configuration, it's value is ignored (only existence is checked), leading to wrong configuration or in best case, some `uninitialized value` warnings.
> aii-ks: spma uses boolean_yes_no for proxy enabling

- aii-ks/src/test/perl/kickstart_pre.t
- aii-ks/src/test/resources/regexps/pre_blocksize_blockdevices
Changes introduced in https://github.com/quattor/ncm-lib-blockdevices/pull/51 lead to new output, so the regexps in the unittests needed modification
> ks: fix unittest regexps due to new output from ncm-lib-blockdevices

- aii-opennebula/src/main/perl/opennebula.pm
- aii-opennebula/src/main/perl/opennebula.pod
* Fix #142 : include support to set different cloud domains into /etc/aii/opennebula.conf
> aii-opennebula: include support to set different RPC cloud domains

- aii-ks/src/main/perl/ks.pm
- aii-ks/src/test/resources/regexps/kickstart_yum_setup
> ks: double escaped variables in yum.conf heredoc-in-heredoc

- aii-opennebula/src/main/pan/quattor/aii/opennebula/default.pan
without this, template-library-core fails for https://github.com/quattor/template-library-core/pull/99
> aii-opennebula: var without default

- aii-ks/src/main/pan/quattor/aii/ks/config.pan
- aii-ks/src/main/pan/quattor/aii/ks/schema.pan
- aii-ks/src/main/perl/ks.pod
- aii-ks/src/test/perl/kickstart_commands.t
- aii-ks/src/test/perl/kickstart_el7_static_ip.t
- aii-ks/src/test/resources/kickstart.pan
md5 is too fast, therefore much easier to brute-force.
This changes the default password hashing algorithm to sha512.
> aii-ks: sha512 instead of md5 for password hashes

- aii-ks/src/main/perl/ks.pm
- aii-ks/src/test/perl/kickstart_mounts.t
- aii-ks/src/test/perl/kickstart_pre.t
- aii-ks/src/test/resources/kickstart_mounts.pan
- aii-ks/src/test/resources/kickstart_pre_mdstop.pan
- aii-ks/src/test/resources/kickstart_pre_nomdstop.pan
- aii-ks/src/test/resources/regexps/pre_mdstop_blockdevices
- aii-ks/src/test/resources/regexps/pre_nomdstop_blockdevices
fixes #102 
depends on https://github.com/quattor/ncm-lib-blockdevices/pull/64
On EL7 Anaconda, mdadm should stop the devices at the end of the pre section, 
and should add the --useexisting flag on the already created MD devices.
> ks: add useexisting when using el7 with md

- aii-ks/src/main/perl/ks.pm
Fixes aii reporting with `--debug 5` the yum packages to be installed as
```
[DEBUG]     Adding YUM commands to install ARRAY(0x3f6fdb0),ARRAY(0x3ebbf28),ARRAY(0x40982a0),ARRAY(0x409b130),ARRAY(0x409ac08),ARRAY(0x4093b78),ARRAY(0x3eb84f0),ARRAY(0x4097a18),ARRAY(0x4093e30),ARRAY(0x3eb7b60),ARRAY(0x409b0a0),ARRAY(0x409ad40)
```
> aii-ks: fix yum install packages debug report message

- aii-core/src/main/perl/aii-shellfe
Otherwise a lot of time is wasted generating useless tabcompletion files.
See #193.
This will be used to build a point release of AII.
> Disable CCM tabcompletion during aii-shellfe runs

- aii-core/src/main/perl/Shellfe.pm
- aii-core/src/main/perl/aii-shellfe
Allows to use aii-shellfe without (or with outdated) `profiles-info.xml`.
Depends on #190
Replaces #191 which replaced #185
> Shellfe: profileinfo from dir using dir:// cdburl

- aii-pxelinux/src/main/perl/pxelinux.pm
- aii-pxelinux/src/test/perl/pxelinux_ks_block.t
- aii-pxelinux/src/test/resources/pxelinux_ks_block.pan
We do this for the kickstart URL but it can be useful for parameters
specified in templates using "append" from the profile.
> aii-pxelinux: substitute LOCALHOST on profile append

- pom.xml
It is no longer updated, maven central is used instead. The fact this repository is on a non-standard port can hang maven on some networks.
> Remove stratuslab-srv01.lal.in2p3.fr:8081 as a distribution (maven) repository

- aii-ks/src/main/pan/quattor/aii/ks/config.pan
- aii-ks/src/main/pan/quattor/aii/ks/schema.pan
- aii-ks/src/main/perl/ks.pm
- aii-ks/src/test/resources/kickstart.pan
- aii-pxelinux/src/main/pan/quattor/aii/pxelinux/config.pan
- aii-pxelinux/src/main/pan/quattor/aii/pxelinux/schema.pan
- aii-pxelinux/src/main/perl/pxelinux.pm
- aii-pxelinux/src/test/resources/pxelinux_no_append.pan
- aii-pxelinux/src/test/resources/pxelinux_no_append_block.pan
Solves the reported error in https://github.com/quattor/aii/issues/200 when a macaddress is used as ksdevice
> ks: schema: bonding is optional and best-effort when not defined

- aii-core/src/main/perl/Shellfe.pm
- aii-ks/src/main/perl/ks.pm
Some configuration modules are providing the support for operations that must be done during the installation (AII), e.g. `ncm-opennebula` or `ncm-freeipa`.
Depends on #202
> Allow components as userhooks

- aii-ks/src/main/perl/ks.pm
- aii-ks/src/test/perl/kickstart_logging.t
- aii-ks/src/test/perl/kickstart_nologging_just_method_and_protocol.t
- aii-ks/src/test/resources/regexps/pre_noblock_logging
> aii-ks: fix logging of pre and post script actions for EL7

- aii-opennebula/src/main/pan/quattor/aii/opennebula/schema.pan
- aii-opennebula/src/main/perl/opennebula.pm
- aii-opennebula/src/main/perl/opennebula.pod
- aii-opennebula/src/main/resources/imagetemplate.tt
- aii-opennebula/src/main/resources/tests/profiles/vm.pan
- aii-opennebula/src/main/resources/tests/regexps/aii_imagetemplate/image_template
- aii-opennebula/src/main/resources/tests/regexps/aii_imagetemplate/simple
- aii-opennebula/src/main/resources/tests/regexps/aii_vmtemplate/simple
- aii-opennebula/src/main/resources/tests/regexps/aii_vmtemplate/vm_template
- aii-opennebula/src/main/resources/vmtemplate.tt
- aii-opennebula/src/test/perl/rpcdata.pm
- aii-opennebula/src/test/resources/vm.pan
This PR includes new LABELS feature available since ONE 5.x
* Fix #223 : Handle missing template
* Fix #224 : Include labels feature
* Fix #228: Include SPICE/VNC random passwords
> aii-opennebula: Include ONE labels support

- aii-ks/src/test/resources/regexps/pre_blocksize_blockdevices
Reported during #225 
Tests fail due to `checksize` kickstart code not matching the regexps
Produced kickstart output (incl reporting)
* the VERB lines are from ncm-lib-blockdevices
* the value printed in the pre section is floored first, but shouldn't change between perl versions.
```
```
the issue is the following floating rounding:
```
$  perl -e 'use POSIX qw(floor);$a=(1+0.001)*4000;printf("%d %.30f %d\n", $a, $a, floor($a));'
4003 4003.999999999999545252649113535881 4003
```
> aii-ks: relax test regexp due to fp rounding issues

- aii-opennebula/src/main/pan/quattor/aii/opennebula/schema.pan
- aii-opennebula/src/main/resources/imagetemplate.tt
- aii-opennebula/src/main/resources/tests/profiles/vm.pan
- aii-opennebula/src/main/resources/tests/regexps/aii_imagetemplate/image_template
- aii-opennebula/src/main/resources/tests/regexps/aii_imagetemplate/simple
- aii-opennebula/src/test/perl/rpcdata.pm
- aii-opennebula/src/test/resources/vm.pan
By default ONE uses raw format but it is possible to use qcow2 as well.
Notice that qcow2 is not supported by Ceph storage backends.
* Fix #235 : Add qcow2 image support
> aii-opennebula: Add VM image driver option

- aii-ks/src/main/perl/ks.pm
- aii-ks/src/test/resources/kickstart_pre_blocksize.pan
- aii-ks/src/test/resources/regexps/pre_blocksize_blockdevices
- aii-ks/src/test/resources/regexps/pre_noblock_functions
Related to renaming done in https://github.com/quattor/template-library-core/pull/139 and https://github.com/quattor/ncm-lib-blockdevices/pull/79
Requires https://github.com/quattor/ncm-lib-blockdevices/pull/80
> aii-ks: rename ncm-lib-blockdevices 'correct' to 'validate'

- aii-core/src/main/perl/DHCP.pm
- aii-core/src/main/perl/Shellfe.pm
- aii-core/src/test/perl/dhcp.t
- aii-core/src/test/perl/parallel.t
- aii-core/src/test/perl/shellfe-dhcp.t
- aii-core/src/test/resources/dhcp.cfg
- aii-core/src/test/resources/parallel.cfg
- aii-core/src/test/resources/shellfe-dhcp-1.pan
- aii-core/src/test/resources/shellfe-dhcp-2.pan
- aii-core/src/test/resources/shellfe-dhcp-3.pan
- aii-core/src/test/resources/shellfe-dhcp-4.pan
- aii-core/src/test/resources/shellfe-dhcp-b.pan
- aii-core/src/test/resources/shellfe-dhcp.pan
Enabling parallelism reduces number of daemon restarts and hence reduces time taken to apply changes.
- Adds an option to run part of the code in parallel: the plugins except for dhcp. 
- DHCP changes are now gathered using the AII::DHCP module instead of calling aii-dhcp. 
- DHCP is now started twice at most (in remove and configure phase) . This is done BEFORE the remove and configure (earlier this was done after other plugins for remove cmd)
- Unused options `restartcmd` and `dhcpconf` were removed. A new option `dhcpcfg` is provided, which makes it possible to overwrite the config file for AII::DHCP module
- Requires Perl > 5.10.1 — effectively removing support for EL5.
- Fixes #241
> AII:Shellfe: Add option to run methods in parallel

- aii-core/src/main/perl/DHCP.pm
Likely caused by a switch from debug() to info().
Fixes #257.
Trailing white-space automatically removed by editor.
> Remove stray 1 from info message

- aii-ks/src/main/pan/quattor/aii/ks/schema.pan
- aii-ks/src/main/pan/quattor/aii/ks/variants/sl5.pan
Fixes #262
Backwards incompatible for EL5 setups that do not match variant name `sl5`
> aii-ks: xwindows: depth and resolution are not supported in EL6+

- aii-ks/src/main/perl/ks.pm
- aii-ks/src/main/perl/ks.pod
As is done in aii-pxelinux, so the file can be served by the host
generating the kickstart.
> Allow LOCALHOST in a ksuserscript URL to substituted.

- aii-ks/src/main/perl/ks.pm
- aii-ks/src/test/perl/kickstart_mounts.t
- aii-ks/src/test/resources/kickstart_mounts.pan
Requires quattor/ncm-lib-blockdevices#88
> ks: set useexisting_lv flag for el7

- aii-pxelinux/src/test/perl/pxelinux_hooks.t
Fallout from quattor/CCM#188
Blocking for 18.6.
> pxelinux: Don't check for placeholder now that it has gone

- aii-core/pom.xml
- Required by aii-installfe
Fixes #288
> aii-core: add perl-IPC-Run as a required dependency

- aii-ks/src/main/perl/ks.pm
- aii-ks/src/test/resources/regexps/pre_noblock_functions
- dd errors may be useful to troubleshoot partition wiping
> ks.pm: do not redirect to /dev/null dd erros

- aii-core/src/main/perl/aii-installfe
- Allow to pass aii-shellfe the cdburl to use: particularly usefull
when used from the Aquilon broker (allow the broker to set the cdburl)
Fixes #290
> aii-installfe: add support for --cdburl

- aii-ks/src/main/pan/quattor/aii/ks/config.pan
- aii-ks/src/main/pan/quattor/aii/ks/schema.pan
Since the Perl code ignores ackurl if acklist is defined, it does not
make sense to force populating ackurl in templates.
> aii-ks: Do not define ackurl if it is not needed

- aii-ks/src/main/perl/ks.pm
We have not needed this hack for a while, so let's get rid of it.
> aii-ks: Drop references to ksdevicemode

- aii-pxelinux/src/main/pan/quattor/aii/pxelinux/schema.pan
- aii-pxelinux/src/test/resources/pxelinux_ks_ksdevice_systemd_scheme_1.pan
- aii-pxelinux/src/test/resources/pxelinux_ks_ksdevice_systemd_scheme_2.pan
- aii-pxelinux/src/test/resources/pxelinux_ks_ksdevice_systemd_scheme_3.pan
- aii-pxelinux/src/test/resources/pxelinux_ks_ksdevice_systemd_scheme_4.pan
The regex become way too complex, and it interacts badly with custom
interface names. If the value of "ksdevice" is not one of the special
values understood by Anaconda, then it should rather be an existing
interface.
> aii-pxelinux: Give up regex-based interface name validation

- aii-ks/src/main/perl/ks.pm
Increase the timeout to 5 hours. Leave the standard input connected to
the console, to allow custom commands added by hooks to use the terminal
if they want.
> aii-ks: Offline update service tweaks

- aii-core/src/main/perl/aii-hooks.pod
- aii-ks/src/main/perl/ks.pm
This allows writing a plugin which opportunistically preserves content
(like SSH private host keys or Kerberos keytabs) by mounting the
previous filesystem(s) and copying files to the installer's ramdisk in
the pre_install phase, and restoring such saved files in the
post_install_nochroot phase.
Before RH7, it was possible to use the pre_install_end hook for
restoring such saved content to the newly formatted filesystem(s). But
Anaconda in RH7 wants to format the root filesystem itself, so restoring
the files now needs to happen later.
> aii-ks: Add a new hook for the "%post --nochroot" phase

- aii-ks/src/main/pan/quattor/aii/ks/variants/el7.pan
- aii-ks/src/main/pan/quattor/aii/ks/variants/sl6.pan
- aii-ks/src/main/perl/ks.pm
- aii-ks/src/main/perl/ks.pod
Drop all code referencing end_script, but allow it still being set by
templates.
> aii-ks: end_script removal, try #2

- aii-ks/src/main/pan/quattor/aii/ks/config.pan
- aii-ks/src/main/pan/quattor/aii/ks/schema.pan
- aii-ks/src/main/perl/ks.pod
Trying to support both ackurl and acklist is a bit awkward, and does not
have much benefits. Mark ackurl as deprecated. This should resolve #317.
> aii-ks: Deprecate ackurl

- aii-ks/src/main/perl/ks.pm
Recent Perl versions iterate over hashes in a random order. While this
does not directly affect functionality, the resulting random updates
to the generated Kickstart files make it difficult to spot real changes.
Add a few "sort" operators to make the output deterministic.
> aii-ks: Avoid spurious changes in the output

- aii-ks/src/test/resources/regexps/pre_blocksize_blockdevices
`wipe_metadata` is no longer conditional, nor does it take a size argument.
This was caused by the changes merged in quattor/ncm-lib-blockdevices@7ee1375ee8db9edda1b030d6de259a2d3eae2ae9.
> aii-ks: Update regex tests to handle wipefs changes in ncm-lib-blockdevices

- aii-ks/src/main/perl/ks.pm
- aii-ks/src/test/resources/regexps/pre_noblock_functions
Keep the previous custom wiping function for RHEL5 for a little longer.
This branch depends on https://github.com/quattor/ncm-lib-blockdevices/pull/93 due to removal of the `rereadpt` function.
> Use wipefs for RHEL6+

- aii-core/pom.xml
Explicitly mark them as such otherwise they get marked with `%doc` in some build environments.
> aii-core: Binaries and Perl modules are not documentation

- aii-ks/src/main/perl/ks.pm
- aii-ks/src/test/perl/kickstart_postreboot.t
Current mailx options used in aii doesn't seem to send mail when s-nail is used, provide correct options when s-nail binary exists.
Fixes #342
> aii/ks: support for sending mail in el9 using correct s-nail format

- aii-ks/src/main/perl/ks.pm
- aii-ks/src/test/resources/regexps/kickstart_yum_setup
Looks like on e.g. EL9, /tmp is tmpfs during postinstall (if no dedicated partition is used for /tmp in the filesystem layout ofcourse)
> /var/tmp is supposed to be reboot persistent

- aii-ks/src/main/pan/quattor/aii/ks/config.pan
- aii-ks/src/main/pan/quattor/aii/ks/variants/el7.pan
- Used to be the case in EL7 but defined in the EL7 variant and lost afterwards
> Define default installation boot protocol as static

- aii-ks/src/main/pan/quattor/aii/ks/config.pan
- aii-ks/src/main/pan/quattor/aii/ks/variants/el8.pan
- aii-ks/src/main/pan/quattor/aii/ks/variants/el9.pan
- aii-pxelinux/src/main/pan/quattor/aii/pxelinux/config.pan
Fixes problems detected during [24.10.0-rc4](https://github.com/quattor/release/issues/365)
> Fixes for EL9 support
